version: 3.4.90.{build}

os: Visual Studio 2017

platform:
    - x64

environment:
    QTDIR: C:\Qt\5.11\msvc2017_64

configuration:
    - Release

clone_folder: C:\projects\MellowPlayer

build_script:
    - cd C:\projects\MellowPlayer\scripts\ci\windows
    - build.bat
    - cd C:\projects\MellowPlayer\scripts\packaging\windows
    - make_installer.bat

test_script:
    - cd C:\projects\MellowPlayer\scripts\ci\windows
    - tests.bat

deploy:
    - provider: BinTray
      username: colinduquesnoy
      api_key:
          secure: 5JxFMiIEPLEzENmBD2AV6eOfA7+9kTfh276P91CoijHfboWrdgvpvci9vuiOxXRa
      subject: colinduquesnoy
      repo: MellowPlayer
      package: WindowsInstaller
      version: 3.4.90.{build}
      publish: true
      override: true
      explode: true

artifacts:
    - path: MellowPlayer_Setup.exe
      name: WindowsInstaller
