version: "3.4.90.{build}"

os: Visual Studio 2017

platform:
    - x64

environment:
    QTDIR: C:\Qt\5.11\msvc2017_64

configuration:
    - Release

clone_folder: C:\projects\MellowPlayer

build_script:
    - cd C:\projects\MellowPlayer\scripts\ci\windows
    - build.bat

test_script:
    - cd C:\projects\MellowPlayer\scripts\ci\windows
    - runtests.bat
