stages:
    - build
    - tests
    - deploy

variables:
    APP_VERSION: '3.7.0'

.linux:
    image: registry.gitlab.com/colinduquesnoy/mellowplayer/build-images/linux:qt515
    variables:
        QT_QPA_PLATFORM: 'offscreen'
    tags:
        - linux

build:debug:
    extends: .linux
    stage: build
    needs: []
    script:
        - ./scripts/ci/linux/build-debug.sh
    artifacts:
        name: "build-debug"
        paths:
            - build

build:release:
    extends: .linux
    stage: build
    needs: []
    script:
        - ./scripts/ci/linux/build-release.sh
    artifacts:
        name: "build-release"
        paths:
            - build

build:release:no-gold-linker:
    extends: .linux
    stage: build
    needs: []
    script:
        - ./scripts/ci/linux/build-release-no-gold-linker.sh

tests:
    extends: .linux
    stage: tests
    needs: ["build:release"]
    dependencies:
        - build:release
    script:
        - ./scripts/ci/linux/tests.sh

coverage:
    extends: .linux
    stage: tests
    needs: ["build:debug"]
    dependencies:
        - build:debug
    script:
        - ./scripts/ci/linux/coverage.sh
    after_script:
        - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}" -f build/coverage.info.cleaned

pages:
    image: alpine:latest
    stage: deploy
    needs: []
    script:
        - echo 'Nothing to do...'
    artifacts:
        paths:
            - public
    only:
        - master