stages:
    - build
    - tests
    - deploy

.linux:
    image: ubuntu:rolling
    variables:
        QT_QPA_PLATFORM: 'offscreen'
        PYTEST_ADDOPTS: '--color=yes'
        DISPLAY: ":99.0"
    tags:
        - linux
    before_script:
        - ./scripts/ci/linux/env-setup.sh


build:linux:
    extends: .linux
    stage: build
    script:
        - ./scripts/ci/linux/build.sh
    artifacts:
        name: "build"
        paths:
        - build


tests:linux:
    extends: .linux
    stage: tests
    dependencies:
        - build:linux
    script:
        - ./scripts/ci/linux/tests.sh


tests:coverage:
    extends: .linux
    stage: tests
    script:
        - ./scripts/ci/linux/coverage.sh


deploy:linux:
    extends: .linux
    stage: deploy
    dependencies:
        - build:linux
    script:
        - ./scripts/ci/linux/deploy.sh
    artifacts:
        name: "AppImage"
        paths:
            - MellowPlayer-x86_64.AppImage
