stages:
    - build
    - tests
    - package
    - deploy

variables:
    VERSION: '3.4.90.${CI_PIPELINE_IID}'

.linux:
    image: registry.gitlab.com/colinduquesnoy/mellowplayer/build-images/linux:latest
    variables:
        QT_QPA_PLATFORM: 'offscreen'
        CMAKE_PREFIX_PATH: '/opt/qt/5.11.2/gcc_64'
    tags:
        - linux


build:linux:
    extends: .linux
    stage: build
    script:
        - ./scripts/ci/linux/build.sh
    artifacts:
        name: "build-linux"
        paths:
            - build
            - appdir


tests:linux:
    extends: .linux
    stage: tests
    dependencies:
        - build:linux
    script:
        - ./scripts/ci/linux/tests.sh


tests:coverage:
    extends: .linux
    stage: tests
    script:
        - ./scripts/ci/linux/coverage.sh


appimage:
    extends: .linux
    stage: package
    script:
        - ./scripts/ci/linux/package.sh
    dependencies:
        - build:linux
    artifacts:
        name: "AppImage"
        paths:
            - MellowPlayer-x86_64.AppImage

deploy:continuous:
    image: alpine:latest
    stage: deploy
    only:
        - master@ColinDuquesnoy/MellowPlayer
    dependencies:
        - appimage
    script:
        - apk add --no-cache curl
        - curl -T MellowPlayer-x86_64.AppImage -ucolinduquesnoy:${BINTRAY_API_KEY} https://api.bintray.com/content/colinduquesnoy/MellowPlayer/Continuous/${VERSION}/MellowPlayer-x86_64.AppImage

deploy:stable:
    image: alpine:latest
    stage: deploy
    only:
        - tags
    dependencies:
        - appimage
    script:
        - apk add --no-cache curl
        - curl -T MellowPlayer-x86_64.AppImage -ucolinduquesnoy:${BINTRAY_API_KEY} https://api.bintray.com/content/colinduquesnoy/MellowPlayer/Stable/${VERSION}/MellowPlayer-x86_64.AppImage

pages:
    image: alpine:latest
    stage: deploy
    script:
        - echo 'Nothing to do...'
    artifacts:
        paths:
            - public
    only:
        - master
