stages:
    - build
    - tests
    - deploy
    - metrics

.linux:
    image: ubuntu:latest
    variables:
        DISPLAY: ':99.0'
        QT_QPA_PLATFORM: 'offscreen'
        TERM: 'xterm-256color'
    tags:
        - linux
    before_script:
        - ./scripts/ci/linux/env-setup.sh


build:linux:
    extends: .linux
    stage: build
    script:
        - ./scripts/ci/linux/build.sh
    artifacts:
        name: "build"
        paths:
        - build


tests:linux:
    extends: .linux
    stage: tests
    dependencies:
        - build:linux
    script:
        - ./scripts/ci/linux/tests.sh


coverage:
    extends: .linux
    stage: metrics
    script:
        - ./scripts/ci/linux/coverage.sh


#deploy:linux:
#    extends: .linux
#    stage: deploy
#    script:
#        - ./scripts/ci/linux/deploy.sh
#    artifacts:
#        name: "AppImage"
#        paths:
#            - MellowPlayer-x86_64.AppImage

pages:
    image: alpine:latest
    stage: deploy
    script:
        - echo 'Nothing to do...'
    artifacts:
        paths:
            - public
    only:
        - master
