stages:
    - build
    - tests
    - deploy
    - metrics

.linux:
    image: registry.gitlab.com/colinduquesnoy/mellowplayer/build-images/linux:latest
    variables:
        QT_QPA_PLATFORM: 'offscreen'
        CMAKE_PREFIX_PATH: '/opt/qt/5.11.2/gcc_64'
    tags:
        - linux


build:linux:
    extends: .linux
    stage: build
    script:
        - ./scripts/ci/linux/build.sh
    artifacts:
        name: "build"
        paths:
            - build
            - appdir


tests:linux:
    extends: .linux
    stage: tests
    dependencies:
        - build:linux
    script:
        - ./scripts/ci/linux/tests.sh


coverage:
    extends: .linux
    stage: metrics
    script:
        - ./scripts/ci/linux/coverage.sh


deploy:linux:
    extends: .linux
    stage: deploy
    script:
        - ./scripts/ci/linux/deploy.sh
    dependencies:
        - build:linux
    artifacts:
        name: "AppImage"
        paths:
            - MellowPlayer-x86_64.AppImage

pages:
    image: alpine:latest
    stage: deploy
    script:
        - echo 'Nothing to do...'
    artifacts:
        paths:
            - public
    only:
        - master
