stages:
    - build
    - tests
    - deploy

.linux:
    image: registry.gitlab.com/colinduquesnoy/mellowplayer/build-images/linux:latest
    variables:
        QT_QPA_PLATFORM: 'offscreen'
        CMAKE_PREFIX_PATH: '/opt/qt/5.11.2/gcc_64'
    tags:
        - linux

.windows:
    image: windows/servercore:ltsc201
    tags:
        - windows


build:linux:
    extends: .linux
    stage: build
    script:
        - ./scripts/ci/linux/build.sh
    artifacts:
        name: "build-linux"
        paths:
            - build
            - appdir

build:windows:
    extends: .windows
    stage: build
    script:
        - dir

tests:linux:
    extends: .linux
    stage: tests
    dependencies:
        - build:linux
    script:
        - ./scripts/ci/linux/tests.sh


tests:coverage:
    extends: .linux
    stage: tests
    script:
        - ./scripts/ci/linux/coverage.sh


AppImage:
    extends: .linux
    stage: deploy
    script:
        - ./scripts/ci/linux/deploy.sh
    dependencies:
        - build:linux
    artifacts:
        name: "AppImage"
        paths:
            - MellowPlayer-x86_64.AppImage

pages:
    image: alpine:latest
    stage: deploy
    script:
        - echo 'Nothing to do...'
    artifacts:
        paths:
            - public
    only:
        - master
